### PR TITLE
Remove unstable let-else statements from cw-ownable-derive.

### LINKED ISSUE #10: Remove unstable let-else statements
Currently `cw-ownable-derive` uses unstable let-else statements which causes builds to fail for workspaces that use stable rust. For example: https://github.com/CosmWasm/cw-nfts/pull/109.

### PR DESCRIPTION
**Pull request by 0xekez**
resolves #10 

this will let this crate be used in workspaces that use stable rust.

### CODE REVIEW

**Comment by 0xekez** [comment]
@larry0x if would be great if you wouldn't mind cutting a release with this change (if you'd like to land it), as that'll unblock my cw-nfts PR. though there is absolutely no rush and it can wait for the work week if you're doing weekend things.

**Comment by larry0x** [comment]
I think the let-else syntax has already been stablized in Rust 1.65? 

See: https://twitter.com/m_ou_se/status/1588190804782116864

**Comment by larry0x** [comment]
I have [this CI task](https://github.com/steak-enjoyers/cw-plus-plus/blob/main/.github/workflows/wasm.yaml) that compiles the entire repo into the wasm target using the stable toolchain. If this CI task passes, then crates in this repo should all be usable in CosmWasm + stable Rust.

**Comment by 0xekez** [comment]
you're so right. the CI job ib cw-nfts was using the old Rust version. thanks. :)

https://github.com/CosmWasm/cw-nfts/pull/109/commits/7a0c0c3af79a9f6eea4735b8bb515b17066b5468

**Pull request closed without merging**
